# Spring boot application
spring:
  application:
    name: dubbo-provider-demo
server:
  port: 9090
# Base packages to scan Dubbo Components (e.g @Service , @Reference)
dubbo:
  scan:
    basePackages: io.github.ee.service
  application:
    id: provider
    name: provider
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181
## RegistryConfig Bean
#dubbo.registry.id = my-registry
#dubbo.registry.address = N/A